FROM vault:latest

ENV VAULT_ADDR="http://127.0.0.1:8200"
ENV VAULT_TOKEN=$HOME/.vault-token
WORKDIR /vault/config
ADD config.json /vault/config
RUN vault secrets enable -path=ssh-client-signer ssh \
	vault write ssh-client-signer/config/ca generate_signing_key=true \
	curl -o /etc/ssh/trusted-user-ca-keys.pem http://127.0.0.1:8200/v1/ssh-client-signer/public_key \
	vault read -field=public_key ssh-client-signer/config/ca > /etc/ssh/trusted-user-ca-keys.pem
	vault write ssh-client-signer/roles/my-role role=@config.json
	vault write -field=signed_key ssh-client-signer/sign/my-role \
	public_key=@$HOME/.ssh/id_rsa.pub > signed-cert.pub
CMD ["ssh","-i","~/.ssh/id_rsa","avatao@x.x.x.x"]
